# **Numpy and Pandas**
## **Numpy Array Operations:**

In [2]:
# import numpy and pandas:

import numpy as np
import pandas as pd

# Create a 1D NumPy Array:

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("\n Week 1 Temperatures:")
print(temperatures_w1)


 Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [4]:
# Inspection and Properties

print("\nInspection and Properties:")
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)


Inspection and Properties:
Shape: (7,)
Data Type: float64
Number of Elements: 7


In [8]:
# Array Operations

# Convert Celsius to Fahrenheit

temp_fahrenheit = (temperatures_w1 * 9/5) + 32

print("\nTemperatures in Fahrenheit:")
print(temp_fahrenheit)

# Maximum, Minimum and Mean

max = np.max(temperatures_w1)
min = np.min(temperatures_w1)
mean = np.mean(temperatures_w1)

print("\nMaximum Temperature:", max )
print("Minimum Temperature:", min )
print("Mean Temperature:",mean )


Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [9]:
# Array Slicing and Indexing

# First three days
first_three_days = temperatures_w1[:3]

# Weekend - last two days
weekend = temperatures_w1[-2:]

# Middle three days
middle_three_days = temperatures_w1[2:5]

print("\nArray Slicing:")
print("First Three Days:", first_three_days)
print("Weekend:", weekend)
print("Middle Three Days:", middle_three_days)


Array Slicing:
First Three Days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle Three Days: [20.8 23.4 26.1]


In [10]:
# Create a 2D NumPy Array

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # (Week 1)
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # (Week 2)
])

print("\nTemperatures for Two Weeks:")
print(temperatures)



Temperatures for Two Weeks:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [11]:
# Inspect and Slice the 2D Array

print("\n2D Array Properties:")
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)


2D Array Properties:
Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14


In [13]:
# Extract each week
week1 = temperatures[0]
week2 = temperatures[1]

# Weekend temperatures for both weeks
week1_weekend = temperatures[0, -2:]
week2_weekend = temperatures[1, -2:]

print("\nWeek 1:", week1)
print("Week 2:", week2)

print("\nWeek 1 Weekend:", week1_weekend)
print("Week 2 Weekend:", week2_weekend)


Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Week 1 Weekend: [24.8 21.9]
Week 2 Weekend: [22.8 20.1]


## **Pandas Series**

In [15]:
# Creating Pandas Series

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("\nMarks Series:")
print(marks)


Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [16]:
# Indexing and Slicing

# Integer index position - 1st rank
first_rank = marks.iloc[0]

# Top 3 ranks using loc
top_three = marks.loc[['Rank1', 'Rank2', 'Rank3']]

# 3rd ranked student using iloc
third_rank = marks.iloc[2]

# Boolean mask - marks greater than 90
marks_greater_90 = marks[marks > 90]

print("\nIndexing and Slicing:")
print("1st Rank Mark:", first_rank)

print("\nTop 3 Ranks:")
print(top_three)

print("\n3rd Rank Mark:", third_rank)

print("\nMarks Greater Than 90:")
print(marks_greater_90)


Indexing and Slicing:
1st Rank Mark: 95

Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank Mark: 89

Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


In [17]:
# Manipulating Series

# Modify Rank1 mark to 100
marks.loc['Rank1'] = 100

# Remove Rank5
marks = marks.drop('Rank5')

# Calculate CGPA
cgpa = marks / 10

print("\nManipulating Series:")
print("Updated Marks:")
print(marks)

print("\nCGPA:")
print(cgpa)



Manipulating Series:
Updated Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


## **Pandas DataFrame**

In [19]:
# Creating DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [
        200, 150, 300, 450, 200,
        250, 300, 180, 350, 400
    ]
})

print("\nTransactions DataFrame:")
print(transactions)



Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [21]:
# DATA EXPLORATION

# Display DataFrame
print("\nFull DataFrame:")
print(transactions)


Full DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [22]:
# Head
print("\nHead:")
print(transactions.head())


Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [23]:
# Tail
print("\nTail:")
print(transactions.tail())


Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [24]:
# Column Names
print("\nColumn Names:")
print(transactions.columns)


Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [25]:
# Data Types
print("\nData Types:")
print(transactions.dtypes)


Data Types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [26]:
# Basic Information
print("\nBasic Information:")
transactions.info()


Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [27]:
# Display ProductCategory and Amount
print("\nProductCategory and Amount:")
print(transactions[['ProductCategory', 'Amount']])


ProductCategory and Amount:
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [28]:
# Retrieve last 3 columns
print("\nLast 3 Columns:")
print(transactions.iloc[:, -3:])


Last 3 Columns:
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [29]:
# Filter Region = North and Amount > 200
filtered_transactions = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print("\nNorth Region with Amount Greater Than 200:")
print(filtered_transactions)


North Region with Amount Greater Than 200:
   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [30]:
# Value counts for ProductCategory
print("\nProduct Category Value Counts:")
print(transactions['ProductCategory'].value_counts())


Product Category Value Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [31]:
# Unique values in Region
print("\nUnique Regions:")
print(transactions['Region'].unique())


Unique Regions:
['North' 'South' 'East' 'West']


In [32]:
# Group by Region and find mean Amount
region_mean = transactions.groupby('Region')['Amount'].mean()

print("\nMean Amount by Region:")
print(region_mean)


Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [33]:
# DATAFRAME MANIPULATION

# Modify Amount for TransactionID 102 to 165

transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print("\nAfter modifying TransactionID 102:")
print(transactions)



After modifying TransactionID 102:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [38]:
# Add Discount column = 10% of Amount

transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter Adding Discount Column:")
print(transactions)



After Adding Discount Column:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [36]:
# Remove row with TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
]

print("\nAfter Removing TransactionID 109:")
print(transactions)


After Removing TransactionID 109:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


In [35]:
# Delete Discount column

transactions = transactions.drop(columns=['Discount'])

print("\nAfter Deleting Discount Column:")
print(transactions)


After Deleting Discount Column:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
